version: '3.9'
services:
  auth:
    build: .
    environment:
      - GUNICORN_CMD_ARGS
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      - internal
    depends_on:
      - db
      - redis
  redis:
    image: redis:6-alpine
    networks:
      - internal
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - moviesauth_db:/var/lib/postgresql/data

    networks:
      - internal

networks:
  internal:
    name: moviesauth_network

volumes:
  moviesauth_db:
