version: '3.9'
services:
  auth:
    build: .
    environment:
      - GUNICORN_CMD_ARGS
    networks:
      - internal
  redis:
    image: redis:6-alpine
    networks:
      - internal
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - moviesauth_db:/var/lib/postgresql/data    

networks:
  internal:
    name: moviesauth_network

volumes:
  moviesauth_db:
